[project]
name = "math-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "Costa",email = "costantinocavallo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "agno (>=1.5.1,<2.0.0)",
    "python-a2a (>=0.5.5,<0.6.0)",
    "openai (>=1.79.0,<2.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "a2a-server (>=0.1.4,<0.2.0)"
]

[tool.poetry.group.dev]
optional    = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0"

[tool.poetry]
packages = [{include = "math_agent", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
